var northern = new Object();
var southern = new Object();

northern = {
  bugs: [
    {
      Bug: "Agrias Butterfly",
      Where: 2,
      Value: 3000,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Ant",
      Where: 10,
      Value: 80,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Atlas Moth",
      Where: 13,
      Value: 3000,
      StartTime: 19,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Bagworm",
      Where: 1,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Banded Dragonfly",
      Where: 2,
      Value: 4500,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Bell Cricket",
      Where: 7,
      Value: 430,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Blue Weevil Beetle",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Brown Cicada",
      Where: 13,
      Value: 250,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Centipede",
      Where: 4,
      Value: 300,
      StartTime: 16,
      EndTime: 23,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Cicada Shell",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Citrus Long-horned Beetle",
      Where: 12,
      Value: 350,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Common Bluebottle",
      Where: 2,
      Value: 300,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Common Butterfly",
      Where: 2,
      Value: 160,
      StartTime: 4,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Cricket",
      Where: 7,
      Value: 130,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Cyclommatus Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Damselfly",
      Where: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Darner Dragonfly",
      Where: 2,
      Value: 230,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Diving Beetle",
      Where: 17,
      Value: 800,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Drone Beetle",
      Where: 13,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Dung Beetle",
      Where: 7,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Earth-boring Dung Beetle",
      Where: 7,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Emperor Butterfly",
      Where: 2,
      Value: 4000,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Evening Cicada",
      Where: 13,
      Value: 0,
      StartTime: 4,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Evening Cicada",
      Where: 13,
      Value: 0,
      StartTime: 16,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Firefly",
      Where: 2,
      Value: 300,
      StartTime: 19,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Flea",
      Where: 14,
      Value: 70,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Fly",
      Where: 11,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Giant Cicada",
      Where: 13,
      Value: 0,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Giant Stag",
      Where: 13,
      Value: 0,
      StartTime: 23,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Giant Water Bug",
      Where: 17,
      Value: 2000,
      StartTime: 19,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Giraffe Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Golden Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Goliath Beetle",
      Where: 13,
      Value: 8000,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Grasshopper",
      Where: 7,
      Value: 160,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Great Purple Emperor",
      Where: 2,
      Value: 0,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Hermit Crab",
      Where: 0,
      Value: 1000,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Honeybee",
      Where: 2,
      Value: 200,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Atlas",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Dynastid",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Elephant",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Herucles",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Jewel Beetle",
      Where: 13,
      Value: 2400,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Ladybug",
      Where: 6,
      Value: 200,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Long Locust",
      Where: 7,
      Value: 200,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Madagascan Sunset Moth",
      Where: 2,
      Value: 2500,
      StartTime: 8,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Man-faced Stink Bug",
      Where: 6,
      Value: 1000,
      StartTime: 19,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Mantis",
      Where: 6,
      Value: 430,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Migratory Locust",
      Where: 7,
      Value: 600,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Miyama Stag",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Mole Cricket",
      Where: 18,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Monach Butterfly",
      Where: 2,
      Value: 140,
      StartTime: 4,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Mosquito",
      Where: 2,
      Value: 130,
      StartTime: 17,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Moth",
      Where: 3,
      Value: 130,
      StartTime: 19,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Orchid Mantis",
      Where: 15,
      Value: 2400,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Paper Kite Butterfly",
      Where: 2,
      Value: 1000,
      StartTime: 8,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Peacock Butterfly",
      Where: 2,
      Value: 2500,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Pill Bug",
      Where: 4,
      Value: 250,
      StartTime: 23,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Pondskater",
      Where: 16,
      Value: 130,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Queen Alexandra's Birdwing",
      Where: 2,
      Value: 4000,
      StartTime: 8,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Rainbow Stag",
      Where: 13,
      Value: 6000,
      StartTime: 19,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Raja Brooke's Birdwing",
      Where: 2,
      Value: 2500,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Red Dragonfly",
      Where: 2,
      Value: 180,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Rice Grasshopper",
      Where: 7,
      Value: 160,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Robust Cicada",
      Where: 13,
      Value: 0,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Rosalia Batesi Beetle",
      Where: 12,
      Value: 3000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Saw Stag",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Scarab Beetle",
      Where: 13,
      Value: 0,
      StartTime: 23,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Scorpion",
      Where: 7,
      Value: 8000,
      StartTime: 19,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Snail",
      Where: 8,
      Value: 250,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Spider",
      Where: 1,
      Value: 480,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Stinkbug",
      Where: 6,
      Value: 120,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Tarantula",
      Where: 7,
      Value: 8000,
      StartTime: 19,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Tiger Beetle",
      Where: 7,
      Value: 1500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Tiger Butterfly",
      Where: 2,
      Value: 240,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Violin Beetle",
      Where: 12,
      Value: 450,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Walker Cicada",
      Where: 13,
      Value: 400,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Walking Leaf",
      Where: 5,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Walking Stick",
      Where: 1,
      Value: 0,
      StartTime: 4,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Walking Stick",
      Where: 1,
      Value: 0,
      StartTime: 17,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Wasp",
      Where: 1,
      Value: 2500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Wharf Roach",
      Where: 9,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Yellow Butterfly",
      Where: 2,
      Value: 160,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    }
  ],
  fish: [
    {
      Fish: "Anchovy",
      Location: 5,
      ShadowType: 1,
      Value: 200,
      StartTime: 4,
      EndTime: 21,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Angelfish",
      Location: 2,
      ShadowType: 1,
      Value: 3000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Arapaima",
      Location: 2,
      ShadowType: 5,
      Value: 10000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Arowana",
      Location: 2,
      ShadowType: 3,
      Value: 10000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Barred Knifejaw",
      Location: 5,
      ShadowType: 2,
      Value: 5000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Barreleye",
      Location: 5,
      ShadowType: 1,
      Value: 15000,
      StartTime: 21,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Betta",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Bitterling",
      Location: 2,
      ShadowType: 0,
      Value: 900,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Black Bass",
      Location: 2,
      ShadowType: 3,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Blowfish",
      Location: 5,
      ShadowType: 2,
      Value: 5000,
      StartTime: 18,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Blue Marlin",
      Location: 0,
      ShadowType: 4,
      Value: 10000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Bluegill",
      Location: 2,
      ShadowType: 1,
      Value: 180,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Butterfly Fish",
      Location: 5,
      ShadowType: 1,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Carp",
      Location: 1,
      ShadowType: 3,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Catfish",
      Location: 1,
      ShadowType: 3,
      Value: 800,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Char",
      Location: 3,
      ShadowType: 2,
      Value: 3800,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Cherry Salmon",
      Location: 2,
      ShadowType: 2,
      Value: 1000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Clown Fish",
      Location: 5,
      ShadowType: 0,
      Value: 650,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Coelacanth",
      Location: 6,
      ShadowType: 5,
      Value: 15000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Crawfish",
      Location: 1,
      ShadowType: 1,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Crucian Carp",
      Location: 2,
      ShadowType: 1,
      Value: 160,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Dab",
      Location: 5,
      ShadowType: 2,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Dace",
      Location: 2,
      ShadowType: 2,
      Value: 240,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Dorado",
      Location: 2,
      ShadowType: 4,
      Value: 15000,
      StartTime: 4,
      EndTime: 21,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Football Fish",
      Location: 5,
      ShadowType: 3,
      Value: 2500,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Freshwater Goby",
      Location: 2,
      ShadowType: 1,
      Value: 400,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Frog",
      Location: 1,
      ShadowType: 1,
      Value: 120,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Gar",
      Location: 1,
      ShadowType: 5,
      Value: 6000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Giant Snakehead",
      Location: 1,
      ShadowType: 4,
      Value: 5500,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Giant Trevally",
      Location: 0,
      ShadowType: 3,
      Value: 4500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Golden Trout",
      Location: 3,
      ShadowType: 3,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Goldfish",
      Location: 1,
      ShadowType: 0,
      Value: 1300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Great White Shark",
      Location: 5,
      ShadowType: 6,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Guppy",
      Location: 2,
      ShadowType: 0,
      Value: 1300,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Hammerhead Shark",
      Location: 5,
      ShadowType: 6,
      Value: 8000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Horse Mackerel",
      Location: 5,
      ShadowType: 1,
      Value: 150,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Killifish",
      Location: 1,
      ShadowType: 0,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "King Salmon",
      Location: 4,
      ShadowType: 0,
      Value: 1800,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Koi",
      Location: 1,
      ShadowType: 3,
      Value: 4000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Loach",
      Location: 2,
      ShadowType: 1,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Mahi-mahi",
      Location: 5,
      ShadowType: 3,
      Value: 6000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Mitten Crab",
      Location: 2,
      ShadowType: 1,
      Value: 2000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Moray Eel",
      Location: 5,
      ShadowType: 7,
      Value: 2000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Napoleonfish",
      Location: 5,
      ShadowType: 5,
      Value: 10000,
      StartTime: 4,
      EndTime: 21,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Neon Tetra",
      Location: 2,
      ShadowType: 0,
      Value: 500,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Nibble Fish",
      Location: 2,
      ShadowType: 1,
      Value: 1500,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Oarfish",
      Location: 5,
      ShadowType: 5,
      Value: 9000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Ocean Sunfish",
      Location: 5,
      ShadowType: 6,
      Value: 4000,
      StartTime: 4,
      EndTime: 21,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Olive Flounder",
      Location: 5,
      ShadowType: 3,
      Value: 800,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Pale Chub",
      Location: 2,
      ShadowType: 0,
      Value: 160,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Pike",
      Location: 2,
      ShadowType: 4,
      Value: 1800,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Piranha",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Piranha",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 21,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Pond Smelt",
      Location: 2,
      ShadowType: 1,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Pop-eyed Goldfish",
      Location: 1,
      ShadowType: 0,
      Value: 1300,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Puffer Fish",
      Location: 5,
      ShadowType: 2,
      Value: 250,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Rainbowfish",
      Location: 2,
      ShadowType: 1,
      Value: 800,
      StartTime: 9,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Ranchu Goldfish",
      Location: 1,
      ShadowType: 1,
      Value: 4500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Ray",
      Location: 5,
      ShadowType: 4,
      Value: 3000,
      StartTime: 4,
      EndTime: 21,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Red Snapper",
      Location: 5,
      ShadowType: 3,
      Value: 3000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Ribbon Eel",
      Location: 5,
      ShadowType: 7,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Saddled Bichir",
      Location: 2,
      ShadowType: 3,
      Value: 4000,
      StartTime: 21,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Salmon",
      Location: 4,
      ShadowType: 1,
      Value: 700,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Saw Shark",
      Location: 5,
      ShadowType: 6,
      Value: 12000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Sea Bass",
      Location: 5,
      ShadowType: 4,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Sea Butterfly",
      Location: 5,
      ShadowType: 0,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Sea Horse",
      Location: 5,
      ShadowType: 0,
      Value: 1100,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Snapping Turtle",
      Location: 2,
      ShadowType: 4,
      Value: 5000,
      StartTime: 21,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Soft-shelled Turtle",
      Location: 2,
      ShadowType: 3,
      Value: 3750,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Squid",
      Location: 5,
      ShadowType: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Stringfish",
      Location: 3,
      ShadowType: 5,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Sturgeon",
      Location: 4,
      ShadowType: 5,
      Value: 10000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Suckerfish",
      Location: 5,
      ShadowType: 6,
      Value: 1500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Surgeonfish",
      Location: 5,
      ShadowType: 1,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Sweetfish",
      Location: 2,
      ShadowType: 2,
      Value: 900,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Tadpole",
      Location: 1,
      ShadowType: 0,
      Value: 100,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Tilapia",
      Location: 2,
      ShadowType: 2,
      Value: 800,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Tuna",
      Location: 0,
      ShadowType: 4,
      Value: 7000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Whale Shark",
      Location: 5,
      ShadowType: 6,
      Value: 13000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Yellow Perch",
      Location: 2,
      ShadowType: 2,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Zebra Turkeyfish",
      Location: 5,
      ShadowType: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    }
  ]
};

southern = {
  bugs: [
    {
      Bug: "Agrias Butterfly",
      Where: 2,
      Value: 3000,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Ant",
      Where: 10,
      Value: 80,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Atlas Moth",
      Where: 13,
      Value: 3000,
      StartTime: 19,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Bagworm",
      Where: 1,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Banded Dragonfly",
      Where: 2,
      Value: 4500,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Bell Cricket",
      Where: 7,
      Value: 430,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Blue Weevil Beetle",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Brown Cicada",
      Where: 13,
      Value: 250,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Centipede",
      Where: 4,
      Value: 300,
      StartTime: 16,
      EndTime: 23,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Cicada Shell",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Citrus Long-horned Beetle",
      Where: 12,
      Value: 350,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Common Bluebottle",
      Where: 2,
      Value: 300,
      StartTime: 4,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Common Butterfly",
      Where: 2,
      Value: 160,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Cricket",
      Where: 7,
      Value: 130,
      StartTime: 17,
      EndTime: 8,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Cyclommatus Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Damselfly",
      Where: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Darner Dragonfly",
      Where: 2,
      Value: 230,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Diving Beetle",
      Where: 17,
      Value: 800,
      StartTime: 8,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Drone Beetle",
      Where: 13,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Dung Beetle",
      Where: 7,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Earth-boring Dung Beetle",
      Where: 7,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Emperor Butterfly",
      Where: 2,
      Value: 4000,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Evening Cicada",
      Where: 13,
      Value: 0,
      StartTime: 4,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Evening Cicada",
      Where: 13,
      Value: 0,
      StartTime: 16,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Firefly",
      Where: 2,
      Value: 300,
      StartTime: 19,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Flea",
      Where: 14,
      Value: 70,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Fly",
      Where: 11,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Giant Cicada",
      Where: 13,
      Value: 0,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Giant Stag",
      Where: 13,
      Value: 0,
      StartTime: 23,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Giant Water Bug",
      Where: 17,
      Value: 2000,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Giraffe Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Golden Stag",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Goliath Beetle",
      Where: 13,
      Value: 8000,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Grasshopper",
      Where: 7,
      Value: 160,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Great Purple Emperor",
      Where: 2,
      Value: 0,
      StartTime: 4,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Hermit Crab",
      Where: 0,
      Value: 1000,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Honeybee",
      Where: 2,
      Value: 200,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Horned Atlas",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Dynastid",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Elephant",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Horned Herucles",
      Where: 13,
      Value: 0,
      StartTime: 17,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Jewel Beetle",
      Where: 13,
      Value: 2400,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Ladybug",
      Where: 6,
      Value: 200,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Long Locust",
      Where: 7,
      Value: 200,
      StartTime: 8,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Madagascan Sunset Moth",
      Where: 2,
      Value: 2500,
      StartTime: 8,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Man-faced Stink Bug",
      Where: 6,
      Value: 1000,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Mantis",
      Where: 6,
      Value: 430,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Migratory Locust",
      Where: 7,
      Value: 600,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Miyama Stag",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Mole Cricket",
      Where: 18,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Bug: "Monach Butterfly",
      Where: 2,
      Value: 140,
      StartTime: 4,
      EndTime: 17,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Mosquito",
      Where: 2,
      Value: 130,
      StartTime: 17,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Moth",
      Where: 3,
      Value: 130,
      StartTime: 19,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Orchid Mantis",
      Where: 15,
      Value: 2400,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Paper Kite Butterfly",
      Where: 2,
      Value: 1000,
      StartTime: 8,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Peacock Butterfly",
      Where: 2,
      Value: 2500,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Pill Bug",
      Where: 4,
      Value: 250,
      StartTime: 23,
      EndTime: 16,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Pondskater",
      Where: 16,
      Value: 130,
      StartTime: 8,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Queen Alexandra's Birdwing",
      Where: 2,
      Value: 4000,
      StartTime: 8,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Rainbow Stag",
      Where: 13,
      Value: 6000,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Bug: "Raja Brooke's Birdwing",
      Where: 2,
      Value: 2500,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Red Dragonfly",
      Where: 2,
      Value: 180,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Rice Grasshopper",
      Where: 7,
      Value: 160,
      StartTime: 8,
      EndTime: 19,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Robust Cicada",
      Where: 13,
      Value: 0,
      StartTime: 8,
      EndTime: 17,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Rosalia Batesi Beetle",
      Where: 12,
      Value: 3000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Saw Stag",
      Where: 13,
      Value: 0,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Scarab Beetle",
      Where: 13,
      Value: 0,
      StartTime: 23,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Scorpion",
      Where: 7,
      Value: 8000,
      StartTime: 19,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Snail",
      Where: 8,
      Value: 250,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Spider",
      Where: 1,
      Value: 480,
      StartTime: 19,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Stinkbug",
      Where: 6,
      Value: 120,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Tarantula",
      Where: 7,
      Value: 8000,
      StartTime: 19,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Tiger Beetle",
      Where: 7,
      Value: 1500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Tiger Butterfly",
      Where: 2,
      Value: 240,
      StartTime: 4,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Violin Beetle",
      Where: 12,
      Value: 450,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Walker Cicada",
      Where: 13,
      Value: 400,
      StartTime: 8,
      EndTime: 17,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Walking Leaf",
      Where: 5,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Walking Stick",
      Where: 1,
      Value: 0,
      StartTime: 4,
      EndTime: 8,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Walking Stick",
      Where: 1,
      Value: 0,
      StartTime: 17,
      EndTime: 19,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Bug: "Wasp",
      Where: 1,
      Value: 2500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Wharf Roach",
      Where: 9,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Bug: "Yellow Butterfly",
      Where: 2,
      Value: 160,
      StartTime: 4,
      EndTime: 19,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    }
  ],
  fish: [
    {
      Fish: "Anchovy",
      Location: 5,
      ShadowType: 1,
      Value: 200,
      StartTime: 4,
      EndTime: 21,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Angelfish",
      Location: 2,
      ShadowType: 1,
      Value: 3000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Arapaima",
      Location: 2,
      ShadowType: 5,
      Value: 10000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Arowana",
      Location: 2,
      ShadowType: 3,
      Value: 10000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Barred Knifejaw",
      Location: 5,
      ShadowType: 2,
      Value: 5000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Barreleye",
      Location: 5,
      ShadowType: 1,
      Value: 15000,
      StartTime: 21,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Betta",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Bitterling",
      Location: 2,
      ShadowType: 0,
      Value: 900,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Black Bass",
      Location: 2,
      ShadowType: 3,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Blowfish",
      Location: 5,
      ShadowType: 2,
      Value: 5000,
      StartTime: 18,
      EndTime: 4,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Blue Marlin",
      Location: 0,
      ShadowType: 4,
      Value: 10000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Bluegill",
      Location: 2,
      ShadowType: 1,
      Value: 180,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Butterfly Fish",
      Location: 5,
      ShadowType: 1,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Carp",
      Location: 1,
      ShadowType: 3,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Catfish",
      Location: 1,
      ShadowType: 3,
      Value: 800,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Char",
      Location: 3,
      ShadowType: 2,
      Value: 3800,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Cherry Salmon",
      Location: 2,
      ShadowType: 2,
      Value: 1000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Clown Fish",
      Location: 5,
      ShadowType: 0,
      Value: 650,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Coelacanth",
      Location: 6,
      ShadowType: 5,
      Value: 15000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Crawfish",
      Location: 1,
      ShadowType: 1,
      Value: 200,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Crucian Carp",
      Location: 2,
      ShadowType: 1,
      Value: 160,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Dab",
      Location: 5,
      ShadowType: 2,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Dace",
      Location: 2,
      ShadowType: 2,
      Value: 240,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Dorado",
      Location: 2,
      ShadowType: 4,
      Value: 15000,
      StartTime: 4,
      EndTime: 21,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Football Fish",
      Location: 5,
      ShadowType: 3,
      Value: 2500,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Freshwater Goby",
      Location: 2,
      ShadowType: 1,
      Value: 400,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Frog",
      Location: 1,
      ShadowType: 1,
      Value: 120,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Gar",
      Location: 1,
      ShadowType: 5,
      Value: 6000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Giant Snakehead",
      Location: 1,
      ShadowType: 4,
      Value: 5500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Giant Trevally",
      Location: 0,
      ShadowType: 3,
      Value: 4500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Golden Trout",
      Location: 3,
      ShadowType: 3,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Goldfish",
      Location: 1,
      ShadowType: 0,
      Value: 1300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Great White Shark",
      Location: 5,
      ShadowType: 6,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Guppy",
      Location: 2,
      ShadowType: 0,
      Value: 1300,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Hammerhead Shark",
      Location: 5,
      ShadowType: 6,
      Value: 8000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Horse Mackerel",
      Location: 5,
      ShadowType: 1,
      Value: 150,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Killifish",
      Location: 1,
      ShadowType: 0,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "King Salmon",
      Location: 4,
      ShadowType: 0,
      Value: 1800,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Koi",
      Location: 1,
      ShadowType: 3,
      Value: 4000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Loach",
      Location: 2,
      ShadowType: 1,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Mahi-mahi",
      Location: 5,
      ShadowType: 3,
      Value: 6000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Mitten Crab",
      Location: 2,
      ShadowType: 1,
      Value: 2000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 0
    },
    {
      Fish: "Moray Eel",
      Location: 5,
      ShadowType: 7,
      Value: 2000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Napoleonfish",
      Location: 5,
      ShadowType: 5,
      Value: 10000,
      StartTime: 4,
      EndTime: 21,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Neon Tetra",
      Location: 2,
      ShadowType: 0,
      Value: 500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Nibble Fish",
      Location: 2,
      ShadowType: 1,
      Value: 1500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Oarfish",
      Location: 5,
      ShadowType: 5,
      Value: 9000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Ocean Sunfish",
      Location: 5,
      ShadowType: 6,
      Value: 4000,
      StartTime: 4,
      EndTime: 21,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Olive Flounder",
      Location: 5,
      ShadowType: 3,
      Value: 800,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Pale Chub",
      Location: 2,
      ShadowType: 0,
      Value: 160,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Pike",
      Location: 2,
      ShadowType: 4,
      Value: 1800,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Piranha",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Piranha",
      Location: 2,
      ShadowType: 1,
      Value: 2500,
      StartTime: 21,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Pond Smelt",
      Location: 2,
      ShadowType: 1,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Pop-eyed Goldfish",
      Location: 1,
      ShadowType: 0,
      Value: 1300,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Puffer Fish",
      Location: 5,
      ShadowType: 2,
      Value: 250,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Rainbowfish",
      Location: 2,
      ShadowType: 1,
      Value: 800,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Ranchu Goldfish",
      Location: 1,
      ShadowType: 1,
      Value: 4500,
      StartTime: 9,
      EndTime: 16,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Ray",
      Location: 5,
      ShadowType: 4,
      Value: 3000,
      StartTime: 4,
      EndTime: 21,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Red Snapper",
      Location: 5,
      ShadowType: 3,
      Value: 3000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Ribbon Eel",
      Location: 5,
      ShadowType: 7,
      Value: 600,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Saddled Bichir",
      Location: 2,
      ShadowType: 3,
      Value: 4000,
      StartTime: 21,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Salmon",
      Location: 4,
      ShadowType: 1,
      Value: 700,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Saw Shark",
      Location: 5,
      ShadowType: 6,
      Value: 12000,
      StartTime: 16,
      EndTime: 9,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Sea Bass",
      Location: 5,
      ShadowType: 4,
      Value: 400,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Sea Butterfly",
      Location: 5,
      ShadowType: 0,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Sea Horse",
      Location: 5,
      ShadowType: 0,
      Value: 1100,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Snapping Turtle",
      Location: 2,
      ShadowType: 4,
      Value: 5000,
      StartTime: 21,
      EndTime: 4,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Soft-shelled Turtle",
      Location: 2,
      ShadowType: 3,
      Value: 3750,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Squid",
      Location: 5,
      ShadowType: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Stringfish",
      Location: 3,
      ShadowType: 5,
      Value: 15000,
      StartTime: 16,
      EndTime: 9,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Sturgeon",
      Location: 4,
      ShadowType: 5,
      Value: 10000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Suckerfish",
      Location: 5,
      ShadowType: 6,
      Value: 1500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Surgeonfish",
      Location: 5,
      ShadowType: 1,
      Value: 1000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Sweetfish",
      Location: 2,
      ShadowType: 2,
      Value: 900,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Tadpole",
      Location: 1,
      ShadowType: 0,
      Value: 100,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 1,
      Oct: 1,
      Nov: 1,
      Dec: 1
    },
    {
      Fish: "Tilapia",
      Location: 2,
      ShadowType: 2,
      Value: 800,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Tuna",
      Location: 0,
      ShadowType: 4,
      Value: 7000,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 0,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 1,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Whale Shark",
      Location: 5,
      ShadowType: 6,
      Value: 13000,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 0,
      Nov: 0,
      Dec: 1
    },
    {
      Fish: "Yellow Perch",
      Location: 2,
      ShadowType: 2,
      Value: 300,
      StartTime: 0,
      EndTime: 0,
      Jan: 0,
      Feb: 0,
      Mar: 0,
      Apr: 1,
      May: 1,
      Jun: 1,
      Jul: 1,
      Aug: 1,
      Sep: 1,
      Oct: 0,
      Nov: 0,
      Dec: 0
    },
    {
      Fish: "Zebra Turkeyfish",
      Location: 5,
      ShadowType: 2,
      Value: 500,
      StartTime: 0,
      EndTime: 0,
      Jan: 1,
      Feb: 1,
      Mar: 1,
      Apr: 1,
      May: 1,
      Jun: 0,
      Jul: 0,
      Aug: 0,
      Sep: 0,
      Oct: 1,
      Nov: 1,
      Dec: 1
    }
  ]
};

var vm = new Vue({
  el: "#app",
  data: {
    northern: northern,
    southern: southern,
    selectedHemisphere: "Northern"
  }
});
